const fakeDistributors = [
     {
          id_distributeur: 'abc123',
          num_serie: '1234',
          Etat: 'active',
          localisation: 'Paris',
          id_sadm: 'sadm1',
          id_region: 'region1',
          id_region_dynamique: 'region_dyn1',
          acheter_distributeur: null,
          detection_vol: [],
          donner_prix: [],
          faire_commande: [],
          panne: [],
     },
     {
          id_distributeur: 'def456',
          num_serie: '5678',
          Etat: 'inactive',
          localisation: 'Lyon',
          id_sadm: 'sadm2',
          id_region: 'region2',
          id_region_dynamique: 'region_dyn2',
          acheter_distributeur: null,
          detection_vol: [],
          donner_prix: [],
          faire_commande: [],
          panne: [],
     },
     {
          id_distributeur: 'ghi789',
          num_serie: '9012',
          Etat: 'active',
          localisation: 'Marseille',
          id_sadm: 'sadm3',
          id_region: 'region3',
          id_region_dynamique: 'region_dyn3',
          acheter_distributeur: null,
          detection_vol: [],
          donner_prix: [],
          faire_commande: [],
          panne: [],
     },
     {
          id_distributeur: 'jkl012',
          num_serie: '3456',
          Etat: 'inactive',
          localisation: 'Toulouse',
          id_sadm: 'sadm4',
          id_region: 'region4',
          id_region_dynamique: 'region_dyn4',
          acheter_distributeur: null,
          detection_vol: [],
          donner_prix: [],
          faire_commande: [],
          panne: [],
     },
];

exports.fakeDistributors = fakeDistributors;
